### ISSUE TITLE
Error unloading entry IHC Viewer for ihcviewer (HA core-2022.3.3) 

### ISSUE THREAD

**Issue by laageide** [dingusdk/haihcviewer#15]
Hi.
I got this error message when updating from core 2022.3.2 to 2022.3.3.
I have the ELKO (Norwegian) variant of the visual controller.
The IHC Beta Test Integration works as a charm, no issiues there.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ihcviewer/__init__.py:75
Integration: IHC Viewer (documentation)
First occurred: 20:39:28 (1 occurrences)
Last logged: 20:39:28

Error unloading entry IHC Viewer for ihcviewer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/ihcviewer/__init__.py", line 75, in async_unload_entry
    hass.components.frontend.async_remove_panel(hass, URL_PANEL)
TypeError: async_remove_panel() takes 2 positional arguments but 3 were given

**Comment by dingusdk** [comment]
This should be fixed in ihcviewer 2.0.6.
