### ISSUE TITLE
Not able to reinstall IHCViewer

### ISSUE THREAD

**Issue by stonelose** [dingusdk/haihcviewer#24]
I have a fully functioning IHC (beta) integration running in latest version.
Earlier I had HAIHCViewer running too, but when it broke at one point I removed it.
Now I want to reinstall. I have downloaded via HACS, but when I run the setup flow, I get a popup saying that "This controller is already setup".
I suspect there is something left over from the previous installation, but how do I remove it?

I have tried deleting related files from the custom integrations folder, reboots, reinstalls etc.

![image](https://user-images.githubusercontent.com/8758236/207025671-143cf717-5114-4d6c-b93b-96f45d5425bf.png)

**Comment by dingusdk** [comment]
Have you look in the integrations page in HA top see if the IHC Viewer is not already there. It could be there if you just deleted the files last time without removing the integration in HA.
If it is not there you can remove it manually by opening the .storege/core.config_entries files search for ihcviewer and remove the entire {... ihcviewer...} section. Then restart HA.
It this does not help look in the HA log for anything related to IHC/IHCViewer

**Comment by stonelose** [comment]
Removing lines in core.config_entries and restarting did the trick.

Thanks a lot for you efforts bringing us this integration. Much appreciated!
