### ISSUE TITLE
inverse of binary sensor does not work?

### ISSUE THREAD

**Issue by nickdenolf** [dingusdk/haihcviewer#29]
I tried to integrate a binary sensor, but status needed to be inverted.

I used the invert option when adding the sensor, but this did not seem to work?

Had to edit the ihc_manual_setup.yaml to manually add "inverting: true" this to the sensor:

  - id: xxxxxxx
    name: Alarm Status
    type: safety
    inverting: true

**Comment by dingusdk** [comment]
Thanks for reporting this issue

The "inverting: true" was not added correctly in the ihc_manual_setup.yaml file.
It should be fixed in the new 2.0.8 version of the ihcviewer
