### ISSUE TITLE
Can't load after 2.0.9 update

### ISSUE THREAD

**Issue by ohaue** [dingusdk/haihcviewer#31]
IHC Viewer can't load after updating to 2.0.9.
If I go back to 2.0.8 it loads again.

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 11.57.51 (1 occurrences)
Last logged: 11.57.51

Error setting up entry IHC Viewer for ihcviewer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ihcviewer/__init__.py", line 70, in async_setup_entry
    hass.data[DOMAIN] =  [ v['controller_id'] for v in hass.data["ihc"].values()]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ihcviewer/__init__.py", line 70, in <listcomp>
    hass.data[DOMAIN] =  [ v['controller_id'] for v in hass.data["ihc"].values()]
                           ~^^^^^^^^^^^^^^^^^
KeyError: 'controller_id'

**Comment by labbs1** [comment]
Same for me...

**Comment by dingusdk** [comment]
Try updating to latest IHC integration 2023.12.1 - this should fix the issue.

**Comment by ohaue** [comment]
That did the trick - 2.0.9 now working - thanks.

Otto

**Comment by labbs1** [comment]
Yepp, works fine.
Thanks!
