### ISSUE TITLE
Ihc viewer cannot startup

### ISSUE THREAD

**Issue by preben529** [dingusdk/haihcviewer#32]
Core            :2024.1.2
Supervisor  :2023.12.0
Os               :11.3
Ihc viever    :2.0.9

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 16.26.35 (2 occurrences)
Last logged: 16.29.21

Error setting up entry IHC Viewer for ihcviewer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ihcviewer/__init__.py", line 70, in async_setup_entry
    hass.data[DOMAIN] =  [ v['controller_id'] for v in hass.data["ihc"].values()]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ihcviewer/__init__.py", line 70, in <listcomp>
    hass.data[DOMAIN] =  [ v['controller_id'] for v in hass.data["ihc"].values()]
                           ~^^^^^^^^^^^^^^^^^
KeyError: 'controller_id'
![image](https://github.com/dingusdk/haihcviewer/assets/81527311/e0c63209-0b07-41c4-9cbd-584bd9ba381c)

**Comment by dingusdk** [comment]
You do not have the newest IHC integration.
I have made a change in version 2024.1.1 of the IHCViewer so it should give a proper error in the log if the controller id is not there.

Note since version 2.xx of the IHCViewer, it does not work with the build in IHC integration in HA.
You need the new integration from [here]https://github.com/dingusdk/haihc-betatest

**Comment by preben529** [comment]
1. if i install the suggested  BETA integration the migration does not create at manual-setup-file
    - and then when reboot, i get this 

    Logger: homeassistant.setup
Source: setup.py:221
First occurred: 20.53.02 (2 occurrences)
Last logged: 20.53.02

Setup failed for custom integration 'ihc': Invalid config.
Setup failed for custom integration 'ihcviewer': (DependencyError(...), 'Could not setup dependencies: ihc')

2. I cant see how to install an old viewer that works with the HA-delivered integration .
