### ISSUE TITLE
Home Assistant warning - The behavior of this method will change in future 

### ISSUE THREAD

**Issue by Infernoken76** [dingusdk/haihcviewer#34]
Logger: py.warnings
Source: /usr/local/lib/python3.11/warnings.py:109
First occurred: February 24, 2024 at 11:16:25 PM (1 occurrences)
Last logged: February 24, 2024 at 11:16:25 PM

/usr/local/lib/python3.11/site-packages/ihcsdk/ihcclient.py:136: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead. if elem:

**Comment by Infernoken76** [comment]
Another one:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:156
First occurred: 11:20:43 AM (1 occurrences)
Last logged: 11:20:43 AM

Detected that custom integration 'ihcviewer' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/ihcviewer/__init__.py, line 102: hass.components.frontend.async_register_built_in_panel(, please report it to the author of the 'ihcviewer' custom integration

**Comment by dingusdk** [comment]
Both issue above should be solved in version 2023.3.1 - you also need the newest ihc integration
